import * as monacoType from 'monaco-editor';
import { conf as javascriptConf, language as javascriptLanguage } from 'monaco-editor/esm/vs/basic-languages/javascript/javascript';
import { conf as typescriptConf, language as typescriptLanguage } from 'monaco-editor/esm/vs/basic-languages/typescript/typescript';
import { conf as pythonConf, language as pythonLanguage } from 'monaco-editor/esm/vs/basic-languages/python/python';
import { conf as javaConf, language as javaLanguage } from 'monaco-editor/esm/vs/basic-languages/java/java';
import { conf as goConf, language as goLanguage } from 'monaco-editor/esm/vs/basic-languages/go/go';
import { conf as rustConf, language as rustLanguage } from 'monaco-editor/esm/vs/basic-languages/rust/rust';
import { conf as cppConf, language as cppLanguage } from 'monaco-editor/esm/vs/basic-languages/cpp/cpp';
import { conf as csharpConf, language as csharpLanguage } from 'monaco-editor/esm/vs/basic-languages/csharp/csharp';
import { conf as sqlConf, language as sqlLanguage } from 'monaco-editor/esm/vs/basic-languages/sql/sql';

interface LanguageDefinition {
  id: string;
  conf: monacoType.languages.LanguageConfiguration;
  language: monacoType.languages.IMonarchLanguage;
}

const LANGUAGE_DEFINITIONS: LanguageDefinition[] = [
  { id: 'javascript', conf: javascriptConf, language: javascriptLanguage },
  { id: 'typescript', conf: typescriptConf, language: typescriptLanguage },
  { id: 'python', conf: pythonConf, language: pythonLanguage },
  { id: 'java', conf: javaConf, language: javaLanguage },
  { id: 'go', conf: goConf, language: goLanguage },
  { id: 'rust', conf: rustConf, language: rustLanguage },
  { id: 'cpp', conf: cppConf, language: cppLanguage },
  { id: 'csharp', conf: csharpConf, language: csharpLanguage },
  { id: 'c', conf: cppConf, language: cppLanguage },
  { id: 'sql', conf: sqlConf, language: sqlLanguage },
];

const isRegistered = (monaco: typeof monacoType, id: string) =>
  monaco.languages.getLanguages().some((lang) => lang.id === id);

const registeredCompletionProviders = new Set<string>();

const KEYWORDS: Record<string, string[]> = {
  python: [
    'and',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'class',
    'continue',
    'def',
    'del',
    'elif',
    'else',
    'except',
    'finally',
    'for',
    'from',
    'global',
    'if',
    'import',
    'in',
    'is',
    'lambda',
    'nonlocal',
    'not',
    'or',
    'pass',
    'raise',
    'return',
    'try',
    'while',
    'with',
    'yield',
  ],
  java: [
    'abstract',
    'assert',
    'boolean',
    'break',
    'byte',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'default',
    'do',
    'double',
    'else',
    'enum',
    'extends',
    'final',
    'finally',
    'float',
    'for',
    'goto',
    'if',
    'implements',
    'import',
    'instanceof',
    'int',
    'interface',
    'long',
    'native',
    'new',
    'package',
    'private',
    'protected',
    'public',
    'return',
    'short',
    'static',
    'strictfp',
    'super',
    'switch',
    'synchronized',
    'this',
    'throw',
    'throws',
    'transient',
    'try',
    'void',
    'volatile',
    'while',
  ],
  go: [
    'break',
    'case',
    'chan',
    'const',
    'continue',
    'default',
    'defer',
    'else',
    'fallthrough',
    'for',
    'func',
    'go',
    'goto',
    'if',
    'import',
    'interface',
    'map',
    'package',
    'range',
    'return',
    'select',
    'struct',
    'switch',
    'type',
    'var',
  ],
  rust: [
    'as',
    'async',
    'await',
    'break',
    'const',
    'continue',
    'crate',
    'dyn',
    'else',
    'enum',
    'extern',
    'false',
    'fn',
    'for',
    'if',
    'impl',
    'in',
    'let',
    'loop',
    'match',
    'mod',
    'move',
    'mut',
    'pub',
    'ref',
    'return',
    'self',
    'Self',
    'static',
    'struct',
    'super',
    'trait',
    'true',
    'type',
    'unsafe',
    'use',
    'where',
    'while',
  ],
  cpp: [
    'alignas',
    'alignof',
    'asm',
    'auto',
    'bool',
    'break',
    'case',
    'catch',
    'char',
    'class',
    'const',
    'constexpr',
    'continue',
    'decltype',
    'default',
    'delete',
    'do',
    'double',
    'else',
    'enum',
    'explicit',
    'export',
    'extern',
    'float',
    'for',
    'friend',
    'goto',
    'if',
    'inline',
    'int',
    'long',
    'mutable',
    'namespace',
    'new',
    'noexcept',
    'nullptr',
    'operator',
    'private',
    'protected',
    'public',
    'register',
    'reinterpret_cast',
    'return',
    'short',
    'signed',
    'sizeof',
    'static',
    'static_cast',
    'struct',
    'switch',
    'template',
    'this',
    'throw',
    'try',
    'typedef',
    'typeid',
    'typename',
    'union',
    'unsigned',
    'using',
    'virtual',
    'void',
    'volatile',
    'wchar_t',
    'while',
  ],
  csharp: [
    'abstract',
    'async',
    'await',
    'bool',
    'break',
    'byte',
    'case',
    'catch',
    'char',
    'checked',
    'class',
    'const',
    'continue',
    'decimal',
    'default',
    'delegate',
    'do',
    'double',
    'else',
    'enum',
    'event',
    'explicit',
    'extern',
    'finally',
    'fixed',
    'float',
    'for',
    'foreach',
    'goto',
    'if',
    'implicit',
    'in',
    'int',
    'interface',
    'internal',
    'is',
    'lock',
    'long',
    'namespace',
    'new',
    'object',
    'operator',
    'out',
    'override',
    'params',
    'private',
    'protected',
    'public',
    'readonly',
    'ref',
    'return',
    'sbyte',
    'sealed',
    'short',
    'sizeof',
    'stackalloc',
    'static',
    'string',
    'struct',
    'switch',
    'this',
    'throw',
    'try',
    'typeof',
    'uint',
    'ulong',
    'unchecked',
    'unsafe',
    'ushort',
    'using',
    'virtual',
    'void',
    'volatile',
    'while',
  ],
  c: [
    'auto',
    'break',
    'case',
    'char',
    'const',
    'continue',
    'default',
    'do',
    'double',
    'else',
    'enum',
    'extern',
    'float',
    'for',
    'goto',
    'if',
    'inline',
    'int',
    'long',
    'register',
    'restrict',
    'return',
    'short',
    'signed',
    'sizeof',
    'static',
    'struct',
    'switch',
    'typedef',
    'union',
    'unsigned',
    'void',
    'volatile',
    'while',
  ],
  sql: [
    'SELECT',
    'FROM',
    'WHERE',
    'INSERT',
    'INTO',
    'VALUES',
    'UPDATE',
    'SET',
    'DELETE',
    'JOIN',
    'INNER',
    'LEFT',
    'RIGHT',
    'FULL',
    'OUTER',
    'ON',
    'GROUP',
    'BY',
    'HAVING',
    'ORDER',
    'LIMIT',
    'OFFSET',
    'DISTINCT',
    'CREATE',
    'TABLE',
    'ALTER',
    'DROP',
    'INDEX',
    'VIEW',
    'TRIGGER',
    'PROCEDURE',
  ],
};

export const registerMonacoLanguages = (monaco: typeof monacoType): void => {
  LANGUAGE_DEFINITIONS.forEach(({ id, conf, language }) => {
    if (!isRegistered(monaco, id)) {
      monaco.languages.register({ id });
      monaco.languages.setMonarchTokensProvider(id, language);
      monaco.languages.setLanguageConfiguration(id, conf);
    }

    if (!registeredCompletionProviders.has(id)) {
      const keywords = KEYWORDS[id];
      if (keywords?.length) {
        monaco.languages.registerCompletionItemProvider(id, {
          provideCompletionItems: (model, position) => {
            const word = model.getWordUntilPosition(position);
            const range = new monaco.Range(
              position.lineNumber,
              word.startColumn,
              position.lineNumber,
              word.endColumn
            );

            const suggestions = keywords.map<monacoType.languages.CompletionItem>((keyword) => ({
              label: keyword,
              kind: monaco.languages.CompletionItemKind.Keyword,
              insertText: keyword,
              range,
            }));

            return { suggestions };
          },
          triggerCharacters: ['.', ' ', ':'],
        });
      }
      registeredCompletionProviders.add(id);
    }
  });
};
